# Logging configurations
logging:
  log_level: "INFO"
  log_file: "logs/pipeline_{date}.log"

# Input/Output Configurations
storage_loc:
  raw: "data/raw"
  bronze: "data/bronze"
  silver: "data/silver"
  gold: "data/gold"
  failed: "data/failed"

# Other Pipeline Configurations
max_retries: 3
retry_delay: 5 # seconds
batch_size: 100
max_map_points: 2000

# Parse configurations
d: "http://www.topografix.com/GPX/1/1"
gpxtpx: "http://www.garmin.com/xmlschemas/TrackPointExtension/v1"
