# Logging configurations
bronze:
  logger_name: "bronze_logger"
  log_level: "INFO"
  log_file: "logs/pipeline_{}.log"
silver:
  logger_name: "silver_logger"
  log_level: "INFO"
  log_file: "logs/pipeline_{}.log"
gold:
  logger_name: "gold_logger"
  log_level: "INFO"
  log_file: "pipeline_{}.log"
pipeline:
  logger_name: "data_pipeline"
  log_level: "INFO"
  log_file: "logs/pipeline_{}.log"

# Input/Output Configurations
storage_loc:
  raw: "data/raw"
  bronze: "data/bronze"
  silver: "data/silver"
  gold: "data/gold"
  failed: "data/failed"

# Other Pipeline Configurations
max_retries: 3
retry_delay: 5 # seconds
